"""made the role column nullable to check if I can do without it in the sign up

Revision ID: 7128fe162a21
Revises: 7e7164375d4b
Create Date: 2024-08-03 12:29:15.570232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7128fe162a21'
down_revision = '7e7164375d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
