"""added the length of the image column to see

Revision ID: e4f6242b5f90
Revises: 15e576284ebd
Create Date: 2024-08-08 14:45:02.588730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f6242b5f90'
down_revision = '15e576284ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=1200),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=1200),
               existing_nullable=True)

    # ### end Alembic commands ###
